#Working deployment with hard-coded secrets
# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: my-access360-linux
# spec:
#   replicas: 1
#   selector:
#     matchLabels:
#       app: my-access360-linux
#   template:
#     metadata:
#       labels:
#         app: my-access360-linux
#     spec:
#       nodeSelector:
#         "kubernetes.io/os": linux
#       containers:
#         - name: logincontainer02
#           image: activedbcontainer.azurecr.io/loginimage
#           ports:
#             # - containerPort: 443
#             - containerPort: 5000
#           env:
#             - name: PRIMARY_DB
#               value: "failovergroupvishal.database.windows.net"
#             - name: SECONDARY_DB
#               value: "failovergroupvishal.secondary.database.windows.net"
#             - name: DB_USER
#               value: "sqladmin"
#             - name: DB_PASSWORD
#               value: "Password123!"
#             - name: DB_NAME
#               value: "sqldbvishal01"



#Working deployment with Azure Key vault

apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-access360-linux
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-access360-linux
  template:
    metadata:
      labels:
        app: my-access360-linux
    spec:
      nodeSelector:
        "kubernetes.io/os": linux
      containers:
        - name: logincontainer02
          image: activedbcontainer.azurecr.io/loginimage:v1-59
          ports:
            # - containerPort: 443
            - containerPort: 5000
          env:
            - name: PRIMARYDB
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: PRIMARYDB
          
            - name: SECONDARYDB
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: SECONDARYDB
          
            - name: DBUSER
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: DBUSER
          
            - name: DBPASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: DBPASSWORD
          
            - name: DBNAME
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: DBNAME

          volumeMounts:
            - name: secrets-store
              mountPath: "/mnt/secrets"
              readOnly: true
      volumes:
        - name: secrets-store
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: "azure-keyvault-secrets"


