apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: azure-keyvault-secrets
spec:
  provider: azure
  secretObjects:                # 👈 THIS enables ENV usage
    - secretName: db-secret
      type: Opaque
      data:
        - objectName: PRIMARY_DB
          key: PRIMARY_DB
        - objectName: SECONDARY_DB
          key: SECONDARY_DB
        - objectName: DB_USER
          key: DB_USER
        - objectName: DB_PASSWORD
          key: DB_PASSWORD
        - objectName: DB_NAME
          key: DB_NAME

  parameters:
    keyvaultName: vishalkeyvault01
    tenantId: 0cb63bd2-5b7b-4fc4-9837-c269e48f1695
    objects: |
      array:
        - |
          objectName: PRIMARY_DB
          objectType: secret
        - |
          objectName: SECONDARY_DB
          objectType: secret
        - |
          objectName: DB_USER
          objectType: secret
        - |
          objectName: DB_PASSWORD
          objectType: secret
        - |
          objectName: DB_NAME
          objectType: secret
