apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: login-service-monitor
  namespace: monitoring
  labels:
    release: monitoring
spec:
  selector:
    matchLabels:
      app: my-access360-linux
  namespaceSelector:
    matchNames:
      - default   # 👈 change if your app is elsewhere
  endpoints:
    - port: http-login
      path: /metrics
      interval: 15s
