apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: login-service-monitor
  namespace: monitoring
  labels:
    release: monitoring   # 🔥 MUST match your helm install
spec:
  selector:
    matchLabels:
      app: my-access360-linux   # 🔥 must match service selector
  namespaceSelector:
    any: true
  endpoints:
    - port: http-login   # 🔥 MUST match your service port name
      path: /metrics
      interval: 15s
